SELECT * FROM TAB;

SELECT * FROM employees;

SELECT LAST_NAME, SALARY FROM EMPLOYEES;

SELECT FIRST_NAME, HIRE_DATE, SALARY, SALARY*12 FROM EMPLOYEES; -- 복수의 컬럼 출력

SELECT SUM(SALARY) FROM EMPLOYEES; -- SALARY의 전체 합

SELECT SUM(SALARY), AVG(SALARY) FROM EMPLOYEES; -- SALARY의 전체 합 및 평균 값

SELECT * FROM DEPARTMENTS;

SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES; -- 중복 제거

SELECT SALARY, SALARY*12 AS 연봉, FIRST_NAME FROM EMPLOYEES; -- AS를 이용한 별칭

SELECT SALARY 월급, SALARY*12 연봉, FIRST_NAME "YOUR NAME" FROM EMPLOYEES; -- AS가 없이 한 칸 띄우고 별칭을 작성해도 된다

SELECT '이름은 : ' || FIRST_NAME || ' 성은 : ' || LAST_NAME FROM EMPLOYEES;

SELECT * FROM LOCATIONS;
SELECT * FROM DEPARTMENTS;

DESC EMPLOYEES;
DESC LOCATIONS;

