
CREATE TABLE ACCOUNT (
    ID VARCHAR2(20) CONSTRAINT ACCOUNT_ID_PK PRIMARY KEY,
    PW VARCHAR2(20),
    NAME VARCHAR2(20),
    PHONE NUMBER,
    EMAIL VARCHAR2(50)
);
CREATE TABLE PASSBOOK (
    PASSBOOKNO NUMBER CONSTRAINT PASSBOOK_PASSBOOKNO_PK PRIMARY KEY,
    ID VARCHAR2(20) CONSTRAINT PASSBOOK_ID_FK REFERENCES ACCOUNT (ID),
    BOOKNUMBER NUMBER CONSTRAINT PASSBOOK_BOOKNUMBER_FK REFERENCES SELLIST (BOOKNUMBER),
    TOTAL NUMBER,
    OPENDATE DATE
);
CREATE TABLE SELLIST (
    BOOKNUMBER NUMBER CONSTRAINT SELLIST_BOOKNUMBER_PK PRIMARY KEY,
    NAME VARCHAR2(50),
    INTEREST NUMBER(4,2),
    SOLD NUMBER(1)
);
CREATE TABLE DEPOWITH (
    DEALNO NUMBER CONSTRAINT DEPOWITH_DEALNO_PK PRIMARY KEY,
    BOOKNUMBER NUMBER CONSTRAINT DEPOWITH_BOOKNUMBER_FK REFERENCES PASSBOOK (PASSBOOKNO),
    OPENDATE DATE,
    WON NUMBER,
    CONTENT VARCHAR2(100),
    TOTAL NUMBER
);
    
    





