-----DML-----

SELECT * FROM REGIONS;
DESC REGIONS;
SELECT * FROM COUNTRIES;

SELECT R.REGION_NAME, C.COUNTRY_NAME, REGION_ID
FROM REGIONS R
    NATURAL JOIN
    COUNTRIES C;
SELECT R.REGION_NAME, C.COUNTRY_NAME, REGION_ID
FROM REGIONS R
    INNER JOIN
    COUNTRIES C
    USING (REGION_ID);


SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'REGIONS';

DESC REGIONS;


------------------INSERT------------------

INSERT INTO REGIONS (REGION_ID, REGION_NAME)
VALUES (5, 'TEST');

INSERT INTO REGIONS (REGION_NAME, REGION_ID)
VALUES('SOUTH POLE', 6);

--COUNTRIES INSERT
DESC COUNTRIES;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'COUNTRIES';
-- KR KOREA 3
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID)
VALUES('KR', 'KOREA', 3);

INSERT INTO COUNTRIES (COUNTRY_ID, REGION_ID)
VALUES ('MC', 4); -- 자동으로 COUNTRY_NAME에 NULL값을 넣게 해주기

INSERT INTO COUNTRIES
VALUES('KR', 'Korea', 3);

INSERT INTO REGIONS (REGION_ID, REGION_NAME) -- 서브쿼리를 이용하여 REGION_ID 값 삽입
VALUES (
    (SELECT MAX(REGION_ID) FROM REGIONS)+1,
    'North Pole');
    
SELECT * FROM SEQ;


------------------UPDATE------------------

UPDATE REGIONS SET REGION_NAME='SPACE'; -- 모든 ROW의 값 변경
UPDATE REGIONS SET REGION_NAME='SPACE' WHERE REGION_ID=4; -- 특정한 ROW의 값만 변경 

-- REGION TABLE에서 제일 마지막에 INSERT한 ROW의 NAME을 SPACE로 수정
UPDATE REGIONS SET REGION_NAME='SPACE' WHERE REGION_ID=
(
    SELECT MAX(REGION_ID) FROM REGIONS
);

SELECT * FROM DEPARTMENTS;

-- 매니저가 없는 부서들의 MANAGER_ID를 200번으로 변경
UPDATE DEPARTMENTS SET MANAGER_ID=200 WHERE MANAGER_ID IS NULL;
UPDATE DEPARTMENTS SET MANAGER_ID=200 WHERE NVL(MANAGER_ID, 0) = 0;


------------------DELETE------------------
SELECT * FROM EMPLOYEES;
DELETE EMPLOYEES;


DELETE REGIONS WHERE REGION_ID=6;
DELETE REGIONS WHERE REGION_ID=2;

-- EMPLOYEES MANAGER인 사원들을 삭제
DELETE EMPLOYEES WHERE EMPLOYEE_ID=206;


----------------------------------------------
DESC DEPARTMENTS;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEPARTMENTS';
SELECT * FROM SEQ;
SELECT * FROM DEPARTMENTS;
-- MANAGER_ID : 200
-- LOCATION_ID : 1800
-- 시퀀스명.NEXTVAL
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES (DEPARTMENTS_SEQ.NEXTVAL, 'TEST', 200, 1800);

DELETE DEPARTMENTS WHERE DEPARTMENT_ID = 360;


ROLLBACK;




