SELECT * FROM NOTICE;
DROP TABLE NOTICE;

SELECT * FROM TAB;

SELECT * FROM USER_CONSTRAINTS;

DROP VIEW EMP_DETAILS_VIEW;
DROP TABLE JOB_HISTORY;
DROP TABLE JOBS;

ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건이름;
-- EMPLOYEES 에서 MANAGER_ID 외래키 삭제
ALTER TABLE EMPLOYEES DROP CONSTRAINT EMP_MANAGER_FK;
-- DEPARTMENTS MANAGER_ID 외래키 삭제
ALTER TABLE DEPARTMENTS DROP CONSTRAINT DEPT_MGR_FK;
-- EMPLOYEES 삭제
DROP TABLE EMPLOYEES;
DROP TABLE DEPARTMENTS;
DROP TABLE LOCATIONS;

DROP TABLE COUNTRIES;
DROP TABLE REGIONS;

SELECT * FROM SEQ;

DROP SEQUENCE CART_SEQ; 
DROP SEQUENCE PRODUCT_SEQ;

COMMIT;



CREATE TABLE BANKBOOK (
    BOOKNUMBER NUMBER CONSTRAINT BB_BN_PK PRIMARY KEY,
    BOOKNAME VARCHAR2(100),
    BOOKCONTENTS VARCHAR2(4000),
    BOOKRATE NUMBER(3,2),
    BOOKSALE NUMBER(1)
);
CREATE SEQUENCE BANKBOOK_SEQ;

DESC BANKBOOK;

COMMIT;

SELECT * FROM BANKBOOK;

DELETE BANKBOOK WHERE BOOKNUMBER = 1;



CREATE TABLE NOTICE(
    NUM NUMBER CONSTRAINT NOTICE_NUM_PK PRIMARY KEY,
    TITLE VARCHAR2(100),
    CONTENTS VARCHAR2(4000),
    WRITER VARCHAR2(100),
    REGDATE DATE,
    HIT NUMBER
);
CREATE SEQUENCE NOTICE_SEQ;

DESC NOTICE;

SELECT * FROM SEQ;

SELECT * FROM NOTICE;

