----- Single Function / TCL -----

-- ABS

SELECT ABS(-10) FROM DUAL;

-- FLOOR
SELECT FLOOR(12.34) FROM DUAL;

-- ROUND
SELECT ROUND(12.45, 1) FROM DUAL;

-- TRUNC
SELECT TRUNC(12.55, 1) FROM DUAL;
SELECT TRUNC(17.45, -1) FROM DUAL;

-- MOD
SELECT MOD (9, 2) FROM DUAL;

-- LENGTH, LENGTHB
SELECT LENGTH('한글') FROM DUAL;
SELECT LENGTHB('한글') FROM DUAL;

-- RPAD
SELECT RPAD('111', 10, 0) FROM DUAL;

-- SUBSTR / LENGTH
SELECT RPAD (SUBSTR('ABCDEF', 1, 1), LENGTH('ABCDEF'), '#') FROM DUAL;
SELECT RPAD (SUBSTR(FIRST_NAME, 1, 1), LENGTH(FIRST_NAME), '#') FROM EMPLOYEES;
SELECT RPAD (SUBSTR(DEPARTMENT_NAME, 1, 1), LENGTH(DEPARTMENT_NAME), '#') FROM DEPARTMENTS;

-- SYSDATE
SELECT SYSDATE, SYSDATE+1 FROM DUAL;

-- NEXT_DAY
SELECT NEXT_DAY(SYSDATE, '일요일') FROM DUAL;

-- TO_CHAR
SELECT TO_CHAR(SYSDATE, 'YYYY,MM,DD') FROM DUAL;
SELECT TO_CHAR(30000000, '999,999,999') FROM DUAL;

SELECT TO_NUMBER('123')*2 FROM DUAL;
SELECT TO_NUMBER('1,222', '9,999') FROM DUAL; -- 괄호안에 순수 숫자만 써놓던가 데이터포맷형을 뒤에 적어줘야한다.

-- 날짜형식 YYYY
SELECT TO_DATE('20211224', 'YYYY-MM-DD') FROM DUAL;
SELECT TO_DATE('21211224 153022', 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;


