-- MYSQL DATABASE 폴더 구분
-- MYSQL은 테이블명, 컬럼명은 대소문자를 구분한다

SHOW DATABASES;

CREATE TABLE BOARD(
	NUM BIGINT AUTO_INCREMENT,
	TITLE VARCHAR(200),
	WRITER VARCHAR(200),
	CONTENTS TEXT,
	HIT BIGINT,
	REGDATE DATE, -- 년월일, DATETIME - 년월일시분초
	REF BIGINT,
	STEP BIGINT,
	DEPTH BIGINT,
	CATEGORY INT, -- 게시판 구별
	CONSTRAINT BOARD_NUM_PK PRIMARY KEY (NUM)
);

DROP TABLE BOARD;

INSERT INTO BOARD (NUM, TITLE, WRITER, CONTENTS, HIT, REGDATE, REF, STEP, DEPTH, CATEGORY)
VALUES (NULL, 'TEST', 'WRITER', 'CONTENTS', 0, NOW(), 0, 0, 0, 1);

SELECT * FROM BOARD;

UPDATE BOARD SET CONTENTS='CONTENTS UPDATE' WHERE NUM = 1;

DELETE FROM BOARD WHERE NUM = 257;




CREATE TABLE BOARDFILES(
	FILENUM BIGINT AUTO_INCREMENT,
	NUM BIGINT,
	FILENAME VARCHAR(200),
	ORINAME VARCHAR(200),
	
	CONSTRAINT BF_FN_PK PRIMARY KEY (FILENUM),
	CONSTRAINT BF_NUM_FK FOREIGN KEY (NUM) REFERENCES BOARD (NUM) ON DELETE CASCADE
);

SELECT * FROM BOARDFILES;

INSERT INTO BOARDFILES
VALUES (NULL, 112, 'FILENAME', 'ORINAME');

DELETE FROM BOARDFILES WHERE NUM = 2;

SELECT * FROM BOARD WHERE NUM > 0 ORDER BY NUM DESC LIMIT 0, 10;

SELECT * FROM BOARD B
		LEFT JOIN
		BOARDFILES BF
		USING(NUM)
		WHERE NUM = 270;


COMMIT;

----------------------------------------------------------------------------------------------

CREATE TABLE MEMBER(
	ID VARCHAR(100),
	PW VARCHAR(100),
	NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	PHONE VARCHAR(100),
	
	CONSTRAINT MEMBER_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE MEMBERFILES(
	FILENUM BIGINT AUTO_INCREMENT,
	ID VARCHAR(100),
	FILENAME VARCHAR(200),
	ORINAME VARCHAR(200),
	
	CONSTRAINT MF_FILENUM_PK PRIMARY KEY (FILENUM),
	CONSTRAINT MF_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID) ON DELETE CASCADE
);


CREATE TABLE ROLE(
	ROLEID BIGINT AUTO_INCREMENT,
	ROLENAME VARCHAR(200),
	
	CONSTRAINT ROLE_ROLEID_PK PRIMARY KEY (ROLEID)
);


CREATE TABLE MEMBERROLE(
	-- MRNUM BIGINT AUTO_INCREMENT,
	ID VARCHAR(200), -- MEMBER ID
	ROLEID BIGINT, -- ROLE ID
	
	CONSTRAINT MR_ID_PK PRIMARY KEY (ID, ROLEID) -- 복합키 (두개의 컬럼을 이용해서 PK로 만드는 것)
);


SELECT * FROM MEMBER;
SELECT * FROM MEMBERFILES;
SELECT * FROM ROLE;
SELECT * FROM MEMBERROLE;

INSERT INTO ROLE (ROLEID, ROLENAME) VALUES (NULL, 'ROLE_ADMIN');
INSERT INTO ROLE (ROLEID, ROLENAME) VALUES (NULL, 'ROLE_MEMBER');
INSERT INTO ROLE (ROLEID, ROLENAME) VALUES (NULL, 'ROLE_SELLER');

INSERT INTO MEMBER (ID, PW, NAME, EMAIL, PHONE) VALUES ('sell1', '1', 'sell1', 'sell1@naver.com', '1');
INSERT INTO MEMBERROLE (ID, ROLEID) VALUES ('sell1', 1);

INSERT INTO MEMBERROLE (ID, ROLEID) VALUES ('A', 1);
INSERT INTO MEMBERROLE (ID, ROLEID) VALUES ('A', 2);

DROP TABLE MEMBER;
DROP TABLE MEMBERFILES;
DROP TABLE MEMBERROLE;

DELETE FROM MEMBER WHERE ID = 'id1';


SELECT M.ID, M.NAME, R.ROLENAME
FROM MEMBER M
	INNER JOIN
	MEMBERROLE MR
	ON M.ID = MR.ID
	LEFT JOIN
	ROLE R
	ON MR.ROLEID = R.ROLEID
WHERE M.ID = 'admin' AND M.PW = '1';




COMMIT;


--------------------------------------------------------------------------------------------------

-- Product
CREATE TABLE PRODUCT(
	PRODUCTNUM BIGINT AUTO_INCREMENT,
	PRODUCTNAME VARCHAR(200),
	PRODUCTPRICE BIGINT,
	PRODUCTCOUNT BIGINT,
	PRODUCTDETAIL LONGTEXT,
	
	CONSTRAINT PR_NUM_PK PRIMARY KEY(PRODUCTNUM)
);

CREATE TABLE PRODUCTFILES(
	FILENUM BIGINT AUTO_INCREMENT,
	PRODUCTNUM BIGINT,
	FILENAME VARCHAR(200),
	ORINAME VARCHAR(200),
	
	CONSTRAINT PF_FN_PK PRIMARY KEY(FILENUM),
	CONSTRAINT PK_PN_FK FOREIGN KEY(PRODUCTNUM) REFERENCES PRODUCT (PRODUCTNUM) ON DELETE CASCADE
);

SELECT * FROM PRODUCT;
SELECT * FROM PRODUCTFILES;

DROP TABLE PRODUCT;
DROP TABLE PRODUCTFILES;

ALTER TABLE PRODUCT MODIFY PRODUCTDETAIL CLOB;
DESC PRODUCT;

ALTER TABLE PRODUCT ADD (ID VARCHAR(200));
ALTER TABLE PRODUCT ADD CONSTRAINT PF_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID) ON DELETE CASCADE;
ALTER TABLE PRODUCT ADD (SALE INT);

UPDATE PRODUCT SET SALE = 1;


SELECT * FROM PRODUCT P
		LEFT JOIN
		PRODUCTFILES PF
		ON P.PRODUCTNUM = PF.PRODUCTNUM
		WHERE P.PRODUCTNUM = 1;
	
DELETE FROM PRODUCT WHERE PRODUCTNUM > 27 AND PRODUCTNUM < 51;

SELECT COUNT(PRODUCTNUM) FROM PRODUCT WHERE
PRODUCTNAME LIKE CONCAT('%', '네오' ,'%');




-- 장바구니
CREATE TABLE CART(
	CARTNUM BIGINT AUTO_INCREMENT,
	ID VARCHAR(200),
	PRODUCTNUM BIGINT,
	COUNT BIGINT,
	REGDATE DATETIME,
	
	CONSTRAINT CART_CN_PK PRIMARY KEY(CARTNUM),
	CONSTRAINT CART_ID_FK FOREIGN KEY(ID) REFERENCES MEMBER(ID) ON DELETE CASCADE,
	CONSTRAINT CART_PN_FK FOREIGN KEY(PRODUCTNUM) REFERENCES PRODUCT(PRODUCTNUM) ON DELETE CASCADE
);

SELECT * FROM CART;

INSERT INTO CART (CARTNUM, ID, PRODUCTNUM, COUNT, REGDATE)
VALUES (NULL, 'id1', 1, 2, now());

COMMIT;


